from typing import Callable, Any, Set

# CLASSES

class Operation:

    # Binary operation acting on two elements of a domain
    # Contains a single dictionary that is the rule for a map
    # Dictionary can either be given directly or generated by a Callable object, in the form of rule

    def __init__(self, domain: Set[Any], rule: dict[tuple[Any, Any], Any] | Callable[[Any, Any], Any]):
        self.domain = domain

        if isinstance(rule, dict):
            self.rule = rule
        else:
            table = {}
            for a in self.domain:
                for b in self.domain:
                    table[(a, b)] = rule(a, b)

            self.rule = table

        if not self.__is_complete__():
            raise ValueError("Operation is not complete. Missing values in Cayley table.")

    def __is_complete__(self) -> bool:
        """Make sure every possible tuple of elements is in the Cayley table."""

        GxG = cartesian_product(self.domain, self.domain)
        domain = set(self.rule.keys())

        return GxG == domain

class Group:
    """Sets closed under an algebraic operation.
    Operation is determined by rule. Give rule either directly as a Cayley table in a dictionary,
    or as a Callable object which takes in two values and outputs one."""

    def __init__(self, elements: Set[Any], rule, identity: Any):
        self.elements = elements
        operation = Operation(elements, rule)

        self.operation = operation
        self.identity = identity

        if not self.__is_closed__():
            raise ValueError("Group is not closed under the operation.")
        elif self.identity not in self.elements:
            raise ValueError("Identity must be in the underlying set.")
        elif not self.__valid_identity__():
            raise ValueError("No valid identity element.")
        elif not self.__inverses_exist__():
            raise ValueError("Invertibility is not satisfied.")
        elif not self.__is_associative__():
            raise ValueError("Operation is not associative.")

    # Check axioms of a group are satisfied

    def __is_closed__(self) -> bool:
        values = set(self.operation.rule.values()) # Values from operation on all possible two elements
        return values <= self.elements # Check the values are all in the group

    def __valid_identity__(self) -> bool:
        rule = self.operation.rule
        e = self.identity

        for a in self.elements:
            if rule[(e,a)] != a or rule[(a,e)] != a:
                return False

        return True

    def __inverses_exist__(self) -> bool:
        rule = self.operation.rule
        e = self.identity

        for a in self.elements:
            inverse_found = False

            for b in self.elements:
                if rule[(a,b)] == e and rule[(b,a)] == e:
                    inverse_found = True
                    break

            if not inverse_found:
                return False

        return True

    def __is_associative__(self) -> bool:
        rule = self.operation.rule
        G = self.elements

        for a in G:
            for b in G:
                for c in G:
                    if rule[(rule[(a, b)], c)] != rule[(a, rule[(b, c)])]:
                        return False
        return True

    def is_abelian(self) -> bool:
        rule = self.operation.rule

        for a in self.elements:
            for b in self.elements:
                if rule[(a,b)] != rule[(b,a)]:
                    return False

        return True

# SPECIFIC GROUPS

class CyclicGroup(Group):

    def __init__(self, n: int):
        f = ModAdd(n)
        elements = set(range(n))
        Group.__init__(self, elements, f, 0)

# OPERATIONS ON GROUPS

def direct_product(G: Group, H: Group) -> Group:
    """Return the direct product Group A x B."""

    raise NotImplementedError


# FUNCTIONS/RULES FOR OPERATIONS

class ModAdd:
    """Family of modular arithmetic binary operations, described by addition mod n."""

    def __init__(self, n: int):
        self.n = n

    def __call__(self, a: int, b: int):
        return (a + b) % self.n

def add(a: int, b: int) -> int:
    return a + b

# MISCELLANEOUS

def cartesian_product(A: Set[Any], B: Set[Any]) -> Set[tuple[Any, Any]]:
    # Useless for now but still successfully makes a Cartesian product so keeping it

    AxB = set()

    for element1 in A:
        for element2 in B:
            AxB.add((element1, element2))

    return AxB

if __name__ == "__main__":
    G = CyclicGroup(5)
    print(G.elements)
    print(G.operation.rule)
